PRAGMA foreign_keys = ON;

BEGIN TRANSACTION;

-- Categories
INSERT INTO faq_categories (name, description, display_order, is_active) VALUES
('General / About JARAMA Global', 'General information about JARAMA Global and its services.', 1, 1),
('Products & Trading', 'Questions about products, specifications, availability and trading.', 2, 1),
('Product Sourcing', 'Questions about sourcing products and suppliers from India.', 3, 1),
('Import Services', 'Questions about import coordination and related services.', 4, 1),
('Export Services', 'Questions about exports and international buyers.', 5, 1),
('Quotation & Orders', 'Questions about quotations, orders, MOQ and timelines.', 6, 1),
('Shipping & Logistics', 'Questions about international shipping and logistics.', 7, 1),
('Documentation & Compliance', 'Questions about trade documents, certificates and compliance.', 8, 1),
('Payment & Commercial Terms', 'Questions about payment terms, Incoterms and commercial conditions.', 9, 1),
('Contact & Enquiries', 'Questions about contacting JARAMA Global and submitting enquiries.', 10, 1);

-- General / About JARAMA Global
INSERT INTO faqs (category_id, button_label, question, answer, action_type, action_value, display_order, is_active)
SELECT id, 'What does JARAMA Global do?', 'What does JARAMA Global do?',
'JARAMA Global provides import, export, product sourcing and international trade support. We work with buyers and suppliers to help coordinate suitable products and trade requirements.',
'ANSWER', NULL, 1, 1 FROM faq_categories WHERE name = 'General / About JARAMA Global';

INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='General / About JARAMA Global'), 'What services do you provide?', 'What services does JARAMA Global provide?', 'Our services may include product sourcing, import and export coordination, quotation support, trade documentation assistance and logistics coordination, depending on the customer''s requirement.', 'ANSWER', NULL, 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;

INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='General / About JARAMA Global'), 'Where are you based?', 'Where is JARAMA Global based?', 'JARAMA Global is an India-based international trading company. Please contact us for our current office and business contact details.', 'ANSWER', NULL, 3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;

INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='General / About JARAMA Global'), 'Do you work internationally?', 'Do you work with international buyers and suppliers?', 'Yes. We work with international business enquiries and can coordinate with buyers and suppliers according to the product, destination and commercial requirements.', 'ANSWER', NULL, 4, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;

INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='General / About JARAMA Global'), 'What markets do you serve?', 'What countries or markets do you serve?', 'We work with international markets depending on the product and transaction requirements. Please share your destination country so we can confirm whether we can support your enquiry.', 'ANSWER', NULL, 5, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;

-- Products & Trading
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Products & Trading'), 'What products do you trade?', 'What products do you import and export?', 'We handle products based on customer requirements and available sourcing opportunities. Please tell us the product you are looking for, and we can review the requirement.', 'ANSWER', NULL, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Products & Trading'), 'Ask about a product', 'Can I ask about a specific product?', 'Yes. Please provide the product name, specifications, required quantity and destination country. Our team can then review the requirement.', 'ENQUIRY_FORM', 'general', 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Products & Trading'), 'Product specifications', 'Can you provide product specifications?', 'Yes, where specifications are available from the supplier or product source. Please tell us the product and the specifications you require.', 'ANSWER', NULL, 3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Products & Trading'), 'Check availability', 'Can you confirm product availability?', 'Availability depends on the product, supplier and order quantity. Send us your requirement and we can check availability.', 'ENQUIRY_FORM', 'general', 4, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Products & Trading'), 'Quality requirements', 'Can you arrange products according to specific quality requirements?', 'We can review sourcing requirements based on product specifications and quality expectations. Please provide the required grade, specifications, standards or certifications.', 'ENQUIRY_FORM', 'general', 5, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;

-- Product Sourcing
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Product Sourcing'), 'Source from India', 'Can you help me source products from India?', 'Yes. We can review product sourcing requirements from India. Please provide the product, quantity, specifications and destination country.', 'ENQUIRY_FORM', 'sourcing', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Product Sourcing'), 'Find a supplier', 'Can you find a supplier for a specific product?', 'We can review your product requirement and explore suitable sourcing options. Supplier availability and suitability will depend on the product and requirements.', 'ENQUIRY_FORM', 'sourcing', 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Product Sourcing'), 'Sourcing requirements', 'What information do you need for a sourcing request?', 'Please provide the product name, specifications or quality requirements, quantity, destination country and required delivery timeline, if applicable.', 'ANSWER', NULL, 3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Product Sourcing'), 'Compare suppliers', 'Can you help compare supplier options?', 'We can review available sourcing options based on factors such as product requirements, quantity, commercial terms and delivery requirements. Final supplier selection should be confirmed by the customer.', 'ANSWER', NULL, 4, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Product Sourcing'), 'Quantity & specifications', 'Can you arrange sourcing based on quantity and specifications?', 'Yes. Quantity and technical specifications are important for sourcing. Please provide the details so we can review suitable options.', 'ENQUIRY_FORM', 'sourcing', 5, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;

-- Import Services
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Import Services'), 'Import assistance', 'Can you help with importing products?', 'Yes. We can assist with import-related trade coordination depending on the product, origin, destination and applicable requirements.', 'ENQUIRY_FORM', 'import', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Import Services'), 'Import into my country', 'Can you arrange products for import into my country?', 'We can review international import enquiries and coordinate suitable options where the product and destination requirements can be supported.', 'ENQUIRY_FORM', 'import', 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Import Services'), 'Import requirements', 'What information is required for an import enquiry?', 'Please provide the product, quantity, origin if known, destination country, specifications, required delivery timeline and any documentation or certification requirements.', 'ANSWER', NULL, 3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Import Services'), 'Import documentation', 'Can you help with import documentation?', 'We can assist with coordinating trade documentation relevant to the transaction. Specific documents depend on the product, origin, destination and applicable regulations.', 'ANSWER', NULL, 4, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Import Services'), 'Import logistics', 'Can you coordinate import logistics?', 'We can assist with logistics coordination depending on the transaction and agreed commercial terms. Please share the shipment details for review.', 'ANSWER', NULL, 5, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;

-- Export Services
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Export Services'), 'Do you support exports?', 'Do you support exports?', 'Yes. We support export-related business enquiries and can coordinate product and trade requirements based on the destination and transaction.', 'ANSWER', NULL, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Export Services'), 'Export to my country', 'Can you export products to my country?', 'Please share your country, product, quantity and specifications. We can review the destination and requirements and advise on the next steps.', 'ENQUIRY_FORM', 'export', 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Export Services'), 'Export process', 'What is the export process?', 'The process generally includes understanding the product requirement, confirming availability and terms, preparing the required documentation, arranging shipment and coordinating delivery.', 'ANSWER', NULL, 3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Export Services'), 'Export enquiry', 'What information do you need for an export enquiry?', 'Please provide the product name, quantity, specifications, destination country, preferred delivery timeline and any special documentation or certification requirements.', 'ENQUIRY_FORM', 'export', 4, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Export Services'), 'Export documents', 'Can you help with export documentation?', 'Yes, we can assist with coordinating the documentation required for an export transaction. The exact documents depend on the product, destination and applicable regulations.', 'ANSWER', NULL, 5, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;

-- Quotation & Orders
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Quotation & Orders'), 'Request a quotation', 'How can I request a quotation?', 'You can send us a quotation enquiry through the website. Please provide the product, quantity, destination and specifications so we can review your requirement.', 'QUOTE_FORM', 'quote', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Quotation & Orders'), 'Quotation requirements', 'What information do you need to prepare a quotation?', 'We normally need the product name, quantity, specifications or quality requirements, destination country and any preferred delivery or commercial terms.', 'ANSWER', NULL, 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Quotation & Orders'), 'What is the MOQ?', 'What is the minimum order quantity (MOQ)?', 'MOQ varies by product and supplier. Please tell us the product and required quantity so we can confirm the applicable MOQ.', 'ANSWER', NULL, 3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Quotation & Orders'), 'Quotation timeline', 'How long does it take to receive a quotation?', 'Quotation time depends on the product, supplier response, specifications and logistics requirements. We will provide an estimated response time after reviewing the enquiry.', 'ANSWER', NULL, 4, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Quotation & Orders'), 'Custom quotation', 'Can I request a quotation for a custom requirement?', 'Yes. Please provide the product specifications, quantity, destination and any other requirements. We can review the request and advise on the available options.', 'QUOTE_FORM', 'quote', 5, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Quotation & Orders'), 'Order timeline', 'How long does an order take?', 'Order timelines depend on product availability, quantity, production or sourcing requirements, documentation and shipping. A more specific estimate can be provided after reviewing the order.', 'ANSWER', NULL, 6, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;

-- Shipping & Logistics
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Shipping & Logistics'), 'Shipping & logistics', 'Do you handle shipping and logistics?', 'We can assist with logistics coordination depending on the transaction and agreed terms. Please share your origin, destination, product and quantity.', 'ANSWER', NULL, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Shipping & Logistics'), 'International shipping', 'Can you arrange international shipping?', 'International shipping can be coordinated depending on the shipment and commercial terms. We can review the requirement and advise on available arrangements.', 'ANSWER', NULL, 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Shipping & Logistics'), 'Shipping methods', 'What shipping methods are available?', 'Shipping options depend on the product, shipment size, destination and required delivery timeline. Available options can be discussed after reviewing the shipment details.', 'ANSWER', NULL, 3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Shipping & Logistics'), 'Delivery time', 'How long does international delivery take?', 'Transit time varies by origin, destination, shipping method, customs and other factors. We can provide an indicative timeline after reviewing the shipment.', 'ANSWER', NULL, 4, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Shipping & Logistics'), 'Shipping estimate', 'Can you provide shipping or delivery estimates?', 'Yes. Please provide the origin, destination, product, quantity and preferred delivery timeline so the shipping requirement can be reviewed.', 'ENQUIRY_FORM', 'shipping', 5, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Shipping & Logistics'), 'Freight responsibility', 'Who is responsible for freight and delivery arrangements?', 'Responsibility depends on the agreed commercial terms and Incoterm for the transaction. The applicable responsibilities should be confirmed in the quotation or order documentation.', 'ANSWER', NULL, 6, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;

-- Documentation & Compliance
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Documentation & Compliance'), 'Required documents', 'What import/export documents are required?', 'Required documents vary by product, origin, destination and transaction. They may include commercial and shipping documents and, where applicable, certificates or other regulatory documents.', 'ANSWER', NULL, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Documentation & Compliance'), 'Trade documentation', 'Can you assist with trade documentation?', 'Yes. We can assist with coordinating documentation relevant to the transaction. The exact requirements should be confirmed based on the product and destination.', 'ANSWER', NULL, 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Documentation & Compliance'), 'Invoices & shipping documents', 'Do you provide invoices and shipping documents?', 'Relevant commercial and shipping documents can be coordinated as part of the transaction, subject to the agreed process and applicable requirements.', 'ANSWER', NULL, 3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Documentation & Compliance'), 'Product certifications', 'Are product certifications required?', 'Certification requirements depend on the product and destination country. Please provide the product and destination so the applicable requirements can be reviewed.', 'ANSWER', NULL, 4, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Documentation & Compliance'), 'Country-specific documents', 'Can you help with country-specific documentation requirements?', 'We can review the documentation requirements associated with the product and destination and coordinate the relevant information where applicable.', 'ANSWER', NULL, 5, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;

-- Payment & Commercial Terms
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Payment & Commercial Terms'), 'Payment methods', 'What payment methods do you accept?', 'Payment methods depend on the transaction and agreed commercial terms. Please contact us with your requirement so the applicable payment options can be discussed.', 'ANSWER', NULL, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Payment & Commercial Terms'), 'Payment terms', 'What payment terms are available?', 'Payment terms are subject to the product, supplier, order value, transaction structure and mutually agreed commercial terms. The applicable terms will be stated in the quotation or order confirmation.', 'ANSWER', NULL, 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Payment & Commercial Terms'), 'Incoterms', 'What are the applicable Incoterms?', 'Incoterms depend on the transaction and shipping arrangement. The applicable Incoterm can be discussed and confirmed in the quotation or commercial documentation.', 'ANSWER', NULL, 3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Payment & Commercial Terms'), 'Payment timing', 'When is payment required?', 'Payment timing depends on the agreed commercial terms. The payment schedule will be confirmed as part of the quotation or order process.', 'ANSWER', NULL, 4, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Payment & Commercial Terms'), 'Discuss commercial terms', 'Can commercial terms be discussed based on the order?', 'Commercial terms may depend on the product, quantity, destination and transaction requirements. Please share your requirement so the appropriate terms can be reviewed.', 'ENQUIRY_FORM', 'commercial', 5, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;

-- Contact & Enquiries
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Contact & Enquiries'), 'How can I contact you?', 'How can I contact JARAMA Global?', 'You can contact JARAMA Global through the contact options provided on our website. For a faster response, include your product and business requirements in your enquiry.', 'CONTACT', 'contact', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Contact & Enquiries'), 'Send a business enquiry', 'How can I send a business enquiry?', 'Use the website enquiry or quotation form and provide your contact details, product requirement, quantity, destination and any relevant specifications.', 'ENQUIRY_FORM', 'general', 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Contact & Enquiries'), 'WhatsApp', 'Can I contact you through WhatsApp?', 'If WhatsApp support is enabled on our website, you can use the WhatsApp contact option to send your enquiry. Please include the key product and quantity details.', 'WHATSAPP', 'contact', 3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Contact & Enquiries'), 'Response time', 'How quickly will you respond to my enquiry?', 'Response time depends on the nature and complexity of the enquiry. We will review the information provided and respond as soon as practical.', 'ANSWER', NULL, 4, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;
INSERT INTO faqs SELECT NULL, (SELECT id FROM faq_categories WHERE name='Contact & Enquiries'), 'Enquiry information', 'What information should I include in my enquiry?', 'Please include your name or company, product, quantity, specifications, destination country, preferred delivery timeline and your contact details.', 'ENQUIRY_FORM', 'general', 5, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP;

COMMIT;

-- Verification
SELECT COUNT(*) AS faq_categories_count FROM faq_categories;
SELECT COUNT(*) AS faqs_count FROM faqs;

SELECT fc.name AS category, COUNT(f.id) AS faq_count
FROM faq_categories fc
LEFT JOIN faqs f ON f.category_id = fc.id
GROUP BY fc.id, fc.name
ORDER BY fc.display_order;
